### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by Chriscaracach**
I added spanish translation for "Why React isn't dying"

### CODE REVIEW

**Comment by TkDodo** [comment]
Thanks. I'm not a fan of medium because they put content behind a pay-wall. Have you considered alternatives like `dev.to` or `hashnode` ?

**Comment by Chriscaracach** [comment]
The truth is that I did not consider it. When I started with this blog, I just searched in the browser and used the first option. Little by little I start to regret using Medium. I might seriously consider moving to dev.to . Thanks for the suggestion

**Comment by Chriscaracach** [comment]
By the way, grat work with Tanstack. I'll start using it, and also translating the blog posts =).

**Comment by TkDodo** [comment]
if you decide to switch, please come back to update the link :) I'll merge this now.

**Pull request merged**
